---
kind: pipeline
type: docker
name: web

steps:
  - name: npm install
    image: node:alpine
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: test
    image: node:alpine
    commands:
      - npm run test

  - name: build
    image: node:alpine
    commands:
      - npm run build

  - name: rsync production
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      hosts:
        - 122.51.238.220
      source: .vuepress/dist/*
      target: /root/doc
      secrets: [ rsync_key ]
  
  # - name: rsync staging
  #   image: drillster/drone-rsync
  #   environment:
  #     RSYNC_KEY:
  #       from_secret: rsync_key
  #   settings:
  #     hosts:
  #       - 47.94.147.222
  #     source: .vuepress/dist/*
  #     target: /root/doc
  #     secrets: [ rsync_key ]
  #   when:
  #     target:
  #       - staging
  #     event:
  #       - promote

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.exmail.qq.com
      port: 
        - 465
      username: yukaimin@jytpay.com
      password: bZh8vXcrzc6METGJ
      from: yukaimin@jytpay.com
    subject: 我的愿望是世界和平
    body: 和平
    when:
      status:
        - failure
        - success